var searchData=
[
  ['main_2ec_15431',['main.c',['../_core_2_src_2main_8c.html',1,'(Глобальное пространство имён)'],['../_drivers_2_c_m_s_i_s_2_d_s_p_2_d_s_p___lib___test_suite_2_common_2src_2main_8c.html',1,'(Глобальное пространство имён)']]],
  ['main_2eh_15432',['main.h',['../main_8h.html',1,'']]],
  ['main_5fs_2ec_15433',['main_s.c',['../main__s_8c.html',1,'']]],
  ['mat_5fadd_2ec_15434',['mat_add.c',['../mat__add_8c.html',1,'']]],
  ['mat_5fadd_5ftests_2ec_15435',['mat_add_tests.c',['../mat__add__tests_8c.html',1,'']]],
  ['mat_5fcmplx_5fmult_2ec_15436',['mat_cmplx_mult.c',['../mat__cmplx__mult_8c.html',1,'']]],
  ['mat_5fcmplx_5fmult_5ftests_2ec_15437',['mat_cmplx_mult_tests.c',['../mat__cmplx__mult__tests_8c.html',1,'']]],
  ['mat_5fhelper_2ec_15438',['mat_helper.c',['../mat__helper_8c.html',1,'']]],
  ['mat_5finit_5ftests_2ec_15439',['mat_init_tests.c',['../mat__init__tests_8c.html',1,'']]],
  ['mat_5finverse_2ec_15440',['mat_inverse.c',['../mat__inverse_8c.html',1,'']]],
  ['mat_5finverse_5ftests_2ec_15441',['mat_inverse_tests.c',['../mat__inverse__tests_8c.html',1,'']]],
  ['mat_5fmult_2ec_15442',['mat_mult.c',['../mat__mult_8c.html',1,'']]],
  ['mat_5fmult_5ffast_5ftests_2ec_15443',['mat_mult_fast_tests.c',['../mat__mult__fast__tests_8c.html',1,'']]],
  ['mat_5fmult_5ftests_2ec_15444',['mat_mult_tests.c',['../mat__mult__tests_8c.html',1,'']]],
  ['mat_5fscale_2ec_15445',['mat_scale.c',['../mat__scale_8c.html',1,'']]],
  ['mat_5fscale_5ftests_2ec_15446',['mat_scale_tests.c',['../mat__scale__tests_8c.html',1,'']]],
  ['mat_5fsub_2ec_15447',['mat_sub.c',['../mat__sub_8c.html',1,'']]],
  ['mat_5fsub_5ftests_2ec_15448',['mat_sub_tests.c',['../mat__sub__tests_8c.html',1,'']]],
  ['mat_5ftrans_2ec_15449',['mat_trans.c',['../mat__trans_8c.html',1,'']]],
  ['mat_5ftrans_5ftests_2ec_15450',['mat_trans_tests.c',['../mat__trans__tests_8c.html',1,'']]],
  ['math_5fhelper_2ec_15451',['math_helper.c',['../_d_s_p___lib___test_suite_2_common_2src_2math__helper_8c.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__convolution__example_2math__helper_8c.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__fir__example_2math__helper_8c.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__graphic__equalizer__example_2math__helper_8c.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__linear__interp__example_2math__helper_8c.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__matrix__example_2math__helper_8c.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__signal__converge__example_2math__helper_8c.html',1,'(Глобальное пространство имён)']]],
  ['math_5fhelper_2eh_15452',['math_helper.h',['../_d_s_p___lib___test_suite_2_common_2inc_2math__helper_8h.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__convolution__example_2math__helper_8h.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__fir__example_2math__helper_8h.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__graphic__equalizer__example_2math__helper_8h.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__linear__interp__example_2math__helper_8h.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__matrix__example_2math__helper_8h.html',1,'(Глобальное пространство имён)'],['../_examples_2_a_r_m_2arm__signal__converge__example_2math__helper_8h.html',1,'(Глобальное пространство имён)']]],
  ['matrix_5ftemplates_2eh_15453',['matrix_templates.h',['../matrix__templates_8h.html',1,'']]],
  ['matrix_5ftest_5fcommon_5fdata_2ec_15454',['matrix_test_common_data.c',['../matrix__test__common__data_8c.html',1,'']]],
  ['matrix_5ftest_5fdata_2eh_15455',['matrix_test_data.h',['../matrix__test__data_8h.html',1,'']]],
  ['matrix_5ftest_5fgroup_2ec_15456',['matrix_test_group.c',['../matrix__test__group_8c.html',1,'']]],
  ['matrix_5ftest_5fgroup_2eh_15457',['matrix_test_group.h',['../matrix__test__group_8h.html',1,'']]],
  ['matrix_5ftests_2eh_15458',['matrix_tests.h',['../matrix__tests_8h.html',1,'']]],
  ['max_2ec_15459',['max.c',['../max_8c.html',1,'']]],
  ['max_5ftests_2ec_15460',['max_tests.c',['../max__tests_8c.html',1,'']]],
  ['mean_2ec_15461',['mean.c',['../mean_8c.html',1,'']]],
  ['mean_5ftests_2ec_15462',['mean_tests.c',['../mean__tests_8c.html',1,'']]],
  ['min_2ec_15463',['min.c',['../min_8c.html',1,'']]],
  ['min_5ftests_2ec_15464',['min_tests.c',['../min__tests_8c.html',1,'']]],
  ['mpu_5farmv7_2eh_15465',['mpu_armv7.h',['../_core_2_include_2mpu__armv7_8h.html',1,'(Глобальное пространство имён)'],['../_include_2mpu__armv7_8h.html',1,'(Глобальное пространство имён)']]],
  ['mpu_5farmv8_2eh_15466',['mpu_armv8.h',['../_core_2_include_2mpu__armv8_8h.html',1,'(Глобальное пространство имён)'],['../_include_2mpu__armv8_8h.html',1,'(Глобальное пространство имён)']]],
  ['mult_2ec_15467',['mult.c',['../mult_8c.html',1,'']]],
  ['mult_5ftests_2ec_15468',['mult_tests.c',['../mult__tests_8c.html',1,'']]]
];
