var searchData=
[
  ['complex_20fft_20tables_19871',['Complex FFT Tables',['../group___c_f_f_t___c_i_f_f_t.html',1,'']]],
  ['class_20marks_20example_19872',['Class Marks Example',['../group___class_marks.html',1,'']]],
  ['complex_20conjugate_19873',['Complex Conjugate',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product_19874',['Complex Dot Product',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20magnitude_19875',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared_19876',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_2dby_2dcomplex_20multiplication_19877',['Complex-by-Complex Multiplication',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['complex_2dby_2dreal_20multiplication_19878',['Complex-by-Real Multiplication',['../group___cmplx_by_real_mult.html',1,'']]],
  ['complex_20matrix_20multiplication_19879',['Complex Matrix Multiplication',['../group___cmplx_matrix_mult.html',1,'']]],
  ['cmsis_19880',['CMSIS',['../group___c_m_s_i_s.html',1,'']]],
  ['core_20definitions_19881',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20register_20bit_20field_20macros_19882',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['cache_20functions_19883',['Cache Functions',['../group___c_m_s_i_s___core___cache_functions.html',1,'']]],
  ['cmsis_20core_20instruction_20interface_19884',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_19885',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['core_20debug_20registers_20_28coredebug_29_19886',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['cmsis_20global_20defines_19887',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_19888',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['convolutional_20neural_20network_20example_19889',['Convolutional Neural Network Example',['../group___c_n_n_example.html',1,'']]],
  ['complex_20fft_20functions_19890',['Complex FFT Functions',['../group___complex_f_f_t.html',1,'']]],
  ['configuration_5fsection_5ffor_5fcmsis_19891',['Configuration_section_for_CMSIS',['../group___configuration__section__for___c_m_s_i_s.html',1,'']]],
  ['convolution_19892',['Convolution',['../group___conv.html',1,'']]],
  ['convolution_20example_19893',['Convolution Example',['../group___convolution_example.html',1,'']]],
  ['correlation_19894',['Correlation',['../group___corr.html',1,'']]],
  ['cortex_19895',['CORTEX',['../group___c_o_r_t_e_x.html',1,'']]],
  ['cortex_20exported_20constants_19896',['CORTEX Exported Constants',['../group___c_o_r_t_e_x___exported___constants.html',1,'']]],
  ['cortex_20exported_20functions_19897',['CORTEX Exported Functions',['../group___c_o_r_t_e_x___exported___functions.html',1,'']]],
  ['cortex_20private_20macros_19898',['CORTEX Private Macros',['../group___c_o_r_t_e_x___private___macros.html',1,'']]],
  ['cortex_20systick_20clock_20source_19899',['CORTEX SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['cosine_19900',['Cosine',['../group__cos.html',1,'']]],
  ['configuration_20functions_19901',['Configuration functions',['../group___e_x_t_i___exported___functions___group1.html',1,'']]],
  ['convert_2032_2dbit_20floating_20point_20value_19902',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['complex_20math_20functions_19903',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['controller_20functions_19904',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['convert_2016_2dbit_20integer_20value_19905',['Convert 16-bit Integer value',['../group__q15__to__x.html',1,'']]],
  ['convert_2032_2dbit_20integer_20value_19906',['Convert 32-bit Integer value',['../group__q31__to__x.html',1,'']]],
  ['convert_208_2dbit_20integer_20value_19907',['Convert 8-bit Integer value',['../group__q7__to__x.html',1,'']]]
];
